name: extracting metadata informtion

on:
  workflow_call:


jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest

    steps:

      - name: Checking out repo
        uses: actions/checkout@v6
        with:
          path: main


      - name: Checking out repo with reusable workflow
        uses: actions/checkout@v6
        with:
          repository: FlorianSchw/dsDemo
          path: workflow


      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::tidyverse, any::here, any::jsonlite, any::desc
          needs: check

      - name: Test the pathing of the runner
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE


      - name: Execute Files
        run: |
          source("R/metadata_extraction.R")
        shell: Rscript {0}

      - name: Verify changes in the data sub-directory
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20
        id: verify-changed-files
        with:
          files: functions_metadata.json

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -am "updating function metadata information"
          git push
