name: pushing datashield metadata information to central repository

on:
  workflow_call:

jobs:
  Copy_Metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Push DataSHIELD function metadata file
        uses: nkoppel/push-files-to-another-repository@v1.1.4
       # env:
        #          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'functions_metadata.json'
          destination-username: 'FlorianSchw'
          destination-repository: 'dsDemo'
          destination-directory: 'datashield_functions_metadata'
          destination-branch: 'master'
          commit-message: 'updated datashield functions metadata'
          commit-username: '${GITHUB_ACTOR}'
          commit-email: '${GITHUB_ACTOR}@users.noreply.github.com'
